-- ============================================================================
-- PAYMENTS TABLE MIGRATION
-- ============================================================================
-- This migration creates the payments table according to the Paystack
-- Implementation Specification in "Paystack steup.md"
--
-- Purpose: Store complete payment data from Paystack for audit, reconciliation,
-- and security. This table is separate from transactions and contains raw
-- payment gateway data.
-- ============================================================================

-- Create payments table with all mandatory fields
CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Core Payment Identifiers (MANDATORY)
  reference VARCHAR(255) UNIQUE NOT NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Payment Amount (MANDATORY - stored in kobo)
  amount BIGINT NOT NULL CHECK (amount > 0),
  currency VARCHAR(3) NOT NULL DEFAULT 'NGN' CHECK (currency = 'NGN'),
  
  -- Payment Status (MANDATORY)
  status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'success', 'failed', 'abandoned')),
  
  -- Customer Information (MANDATORY)
  email VARCHAR(255) NOT NULL,
  
  -- Payment Channel (MANDATORY)
  channel VARCHAR(50) NOT NULL CHECK (channel IN ('card', 'bank', 'ussd', 'qr', 'mobile_money', 'bank_transfer', 'eft')),
  
  -- Paystack Customer Data (MANDATORY for future charges)
  authorization_code VARCHAR(255),
  customer_code VARCHAR(255),
  
  -- Gateway Response (MANDATORY for debugging)
  gateway_response TEXT,
  
  -- Fees (MANDATORY)
  fees BIGINT DEFAULT 0,
  
  -- Payment Timestamp (MANDATORY)
  paid_at TIMESTAMPTZ,
  
  -- Verification Status (MANDATORY - default false)
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  
  -- Metadata (MANDATORY - contains app, user_id, purpose, entity_id)
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  
  -- Additional Paystack Fields (for completeness)
  paystack_id BIGINT,
  transaction_id BIGINT,
  domain VARCHAR(10) CHECK (domain IN ('test', 'live')),
  
  -- Timestamps (MANDATORY)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX idx_payments_reference ON payments(reference);
CREATE INDEX idx_payments_user_id ON payments(user_id);
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_payments_verified ON payments(verified);
CREATE INDEX idx_payments_created_at ON payments(created_at DESC);
CREATE INDEX idx_payments_email ON payments(email);
CREATE INDEX idx_payments_customer_code ON payments(customer_code);

-- GIN index for metadata JSONB queries
CREATE INDEX idx_payments_metadata ON payments USING GIN (metadata);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================
-- Security Rule: Users can only read their own payment records
-- Only backend (service role) can insert/update payments
-- Users CANNOT update verified field or any payment data
-- ============================================================================

-- Enable RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own payments
CREATE POLICY "Users can view their own payments"
  ON payments
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert pending payments (see fix_payments_insert_policy.sql)
-- Users are allowed to create pending payment records when initiating payments
-- Backend verifies and updates payment status via Edge Functions

-- Policy: Only service role can update payments (via Edge Functions)
-- No user-facing policy for UPDATE - only backend can update payments

-- ============================================================================
-- TRIGGER: Update timestamp
-- ============================================================================

CREATE TRIGGER update_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE payments IS 'Stores complete Paystack payment data for audit and reconciliation. Separate from transactions table.';
COMMENT ON COLUMN payments.reference IS 'Unique payment reference from Paystack or generated by frontend';
COMMENT ON COLUMN payments.amount IS 'Amount in kobo (smallest currency unit). 100 kobo = 1 NGN';
COMMENT ON COLUMN payments.verified IS 'Backend verification flag. Only true after successful webhook verification';
COMMENT ON COLUMN payments.metadata IS 'Must contain: app, user_id, purpose, entity_id for proper payment routing';
COMMENT ON COLUMN payments.authorization_code IS 'Reusable authorization for future charges (recurring payments)';
COMMENT ON COLUMN payments.customer_code IS 'Paystack customer identifier for this user';
COMMENT ON COLUMN payments.gateway_response IS 'Raw response message from payment gateway for debugging';
